# shell = 'zsh'

[colors]
draw_bold_text_with_bright_colors = false

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
# background = '#282828'
# soft contrast background = = '#32302f'
# background = "#000000"
# foreground = "#ebdbb2"

# Gruvbox

# Normal colors
# [colors.normal]
# black   = "#000000"
# red     = "#cc241d"
# green   = "#98971a"
# yellow  = "#d79921"
# blue    = "#458588"
# magenta = "#b16286"
# cyan    = "#689d6a"
# white   = "#a89984"

# # Bright colors
# [colors.bright]
# black   = "#7c6f64"
# red     = "#fb4934"
# green   = "#b8bb26"
# yellow  = "#fabd2f"
# blue    = "#83a598"
# magenta = "#d3869b"
# cyan    = "#8ec07c"
# white   = "#ebdbb2"

[font]
size = 9.1
# size = 7.3

[font.normal]
family = 'Source Code Pro'

# family = 'Hack'
# family = 'Consolas'
# family = 'Monospace'

style = 'Regular'

[font.bold]
# style = 'Medium'
# style = 'Bold'
style = 'Semibold'

[font.offset]
x = 0
y = -2

[font.glyph_offset]
x = 0
y = 0

[window]
opacity = 0.92
# opacity = 1

[window.padding]
x = 0
y = 1
